### PR TITLE
Tag and branch cdk-addons upon release

### PR DESCRIPTION
**Pull request by ktsakalozos**
DO NOT MERGE THIS
We need to first create a cdk-ci user with access to cdk-addons repo.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Do we need a way to call build and release snaps without creating the branches and tags?

**Comment by wwwtyro** [comment]
@ktsakalozos Can we talk about this tomorrow morning? I'm trying to understand this approach vs git tag+push.

**Comment by wwwtyro** [comment]
@ktsakalozos lgtm - lmk when you're ready for this to be merged.

**Comment by ktsakalozos** [comment]
@wwwtyro go ahead with the merge. I have already updated the ci jobs to get the new params and I will have to monitor it the next couple of days to see everything works as planned. Thanks

**Pull request merged**
